#!/usr/bin/env bash
#
# 04-install-launcher.sh
#
# Builds a real double-clickable macOS application that launches the
# secondary Claude profile, and installs it into /Applications.
#
# Why build a .app instead of using Script Editor?
#   - Nothing to click through, and it is reproducible.
#   - The result is a plain folder of readable files, so you can open it up
#     and debug it. A Script Editor export is a compiled binary blob.
#   - It is version-controllable.
#
# A macOS .app is just a directory with a required layout:
#
#   Claude Work.app/
#     Contents/
#       Info.plist              metadata telling macOS how to launch it
#       PkgInfo                 legacy 8-byte type/creator file
#       MacOS/
#         launcher              the executable — here, a shell script
#       Resources/
#         AppIcon.icns          the dock icon
#
# Usage:  ./04-install-launcher.sh
#
# ---------------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=config.sh
source "$SCRIPT_DIR/config.sh"

require_macos

# CLAUDE_APP_SECONDARY is normally the same as CLAUDE_APP. It differs only
# if you had to fall back to a cloned app bundle (03-fallback-clone-app.sh).
[ -d "$CLAUDE_APP_SECONDARY" ] \
  || die "App not found at $CLAUDE_APP_SECONDARY (check CLAUDE_APP_SECONDARY in config.sh)"

if [ "$CLAUDE_APP_SECONDARY" != "$CLAUDE_APP" ]; then
  info "Targeting the cloned bundle: $CLAUDE_APP_SECONDARY"
fi

# Build into a staging directory first, then move the finished bundle into
# place. If something fails halfway, /Applications is never left holding a
# half-built app.
BUILD_DIR="$SCRIPT_DIR/build"
STAGED_APP="$BUILD_DIR/${LAUNCHER_APP_NAME}.app"

# The executable name must not contain spaces — CFBundleExecutable is
# fussy about that.
EXECUTABLE_NAME="launcher"


# ---------------------------------------------------------------------------
# 1. Lay out the bundle skeleton
# ---------------------------------------------------------------------------
create_skeleton() {
  header "Creating bundle skeleton"

  rm -rf "$BUILD_DIR"
  mkdir -p "$STAGED_APP/Contents/MacOS"
  mkdir -p "$STAGED_APP/Contents/Resources"

  # PkgInfo: "APPL" = application, "????" = no specific creator code.
  # Modern macOS ignores it, but some tooling still expects it to exist.
  printf 'APPL????' > "$STAGED_APP/Contents/PkgInfo"

  ok "Skeleton created at $STAGED_APP"
}


# ---------------------------------------------------------------------------
# 2. Write the executable
# ---------------------------------------------------------------------------
# The profile path is baked in rather than read from config.sh, so the
# finished .app keeps working even if you move or delete this repo.
write_executable() {
  header "Writing launcher executable"

  local exec_path="$STAGED_APP/Contents/MacOS/$EXECUTABLE_NAME"

  cat > "$exec_path" <<EOF
#!/usr/bin/env bash
#
# Generated by 04-install-launcher.sh — edit config.sh and re-run rather
# than editing this file, or your changes will be overwritten.
#
# Launches Claude desktop against a separate Electron profile directory.

set -euo pipefail

CLAUDE_APP="$CLAUDE_APP_SECONDARY"
PROFILE_DIR="$DESKTOP_SECONDARY_DIR"

# If the real app has been moved or uninstalled, say so in a dialog rather
# than failing silently — there is no terminal attached to see stderr.
if [ ! -d "\$CLAUDE_APP" ]; then
  osascript -e 'display alert "Claude not found" message "Expected the app at $CLAUDE_APP_SECONDARY. Reinstall Claude, or edit config.sh and re-run 04-install-launcher.sh." as critical'
  exit 1
fi

mkdir -p "\$PROFILE_DIR"

exec open -n -a "\$CLAUDE_APP" --args --user-data-dir="\$PROFILE_DIR"
EOF

  chmod +x "$exec_path"
  ok "Wrote $exec_path"
}


# ---------------------------------------------------------------------------
# 3. Write Info.plist
# ---------------------------------------------------------------------------
# Key choices:
#   CFBundleIdentifier  deliberately NOT com.anthropic.claude — this is our
#                       own launcher, and reusing that ID would confuse
#                       macOS about which app is which.
#   LSUIElement         hides the launcher from the Dock and app switcher.
#                       It runs for a fraction of a second and exits; without
#                       this you get a pointless icon flashing in the Dock.
#   LSMinimumSystemVersion  arbitrary but sane floor.
write_info_plist() {
  header "Writing Info.plist"

  cat > "$STAGED_APP/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleName</key>
	<string>${LAUNCHER_APP_NAME}</string>
	<key>CFBundleDisplayName</key>
	<string>${LAUNCHER_APP_NAME}</string>
	<key>CFBundleExecutable</key>
	<string>${EXECUTABLE_NAME}</string>
	<key>CFBundleIdentifier</key>
	<string>local.claudeprofiles.launcher.${PROFILE_NAME}</string>
	<key>CFBundleIconFile</key>
	<string>AppIcon</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>LSMinimumSystemVersion</key>
	<string>11.0</string>
	<key>LSUIElement</key>
	<true/>
	<key>NSHighResolutionCapable</key>
	<true/>
</dict>
</plist>
EOF

  # Fail fast on a malformed plist rather than shipping a bundle macOS
  # will refuse to launch with an unhelpful error.
  if plutil -lint "$STAGED_APP/Contents/Info.plist" >/dev/null 2>&1; then
    ok "Info.plist written and validated"
  else
    die "Generated Info.plist is malformed — this is a bug in this script"
  fi
}


# ---------------------------------------------------------------------------
# 4. Borrow Claude's icon
# ---------------------------------------------------------------------------
# Cosmetic only. A missing icon gives you a blank page icon, which still
# works fine — so every failure here is a warning, never fatal.
copy_icon() {
  header "Copying icon"

  local icon_name
  icon_name="$(defaults read "$CLAUDE_APP_SECONDARY/Contents/Info.plist" CFBundleIconFile 2>/dev/null || echo "")"

  if [ -z "$icon_name" ]; then
    warn "Claude declares no icon file — the launcher will use a generic icon"
    return 0
  fi

  # CFBundleIconFile may or may not include the .icns extension.
  case "$icon_name" in
    *.icns) : ;;
    *) icon_name="${icon_name}.icns" ;;
  esac

  local source_icon="$CLAUDE_APP_SECONDARY/Contents/Resources/$icon_name"

  if [ -f "$source_icon" ]; then
    cp "$source_icon" "$STAGED_APP/Contents/Resources/AppIcon.icns"
    ok "Copied icon from $icon_name"
  else
    warn "Icon not found at $source_icon — using a generic icon"
  fi
}


# ---------------------------------------------------------------------------
# 5. Ad-hoc code signature
# ---------------------------------------------------------------------------
# `--sign -` means "ad-hoc": a signature with no identity attached. It does
# not make the app trusted by Gatekeeper, but recent macOS versions are
# happier launching a signed bundle than an unsigned one. Locally built
# apps have no quarantine flag, so this is belt-and-braces.
sign_bundle() {
  header "Signing bundle (ad-hoc)"

  if codesign --force --sign - "$STAGED_APP" >/dev/null 2>&1; then
    ok "Ad-hoc signature applied"
  else
    warn "Signing failed — the app will probably still launch. Continuing."
  fi
}


# ---------------------------------------------------------------------------
# 6. Install into /Applications
# ---------------------------------------------------------------------------
install_bundle() {
  header "Installing to /Applications"

  local reply
  if [ -e "$LAUNCHER_APP_PATH" ]; then
    warn "$LAUNCHER_APP_PATH already exists"
    read -r -p "Replace it? [y/N] " reply || true
    case "${reply:-}" in
      [yY]*) rm -rf "$LAUNCHER_APP_PATH" ;;
      *) die "Aborted. The built bundle is at $STAGED_APP if you want it." ;;
    esac
  fi

  # /Applications is usually writable by an admin user without sudo.
  if mv "$STAGED_APP" "$LAUNCHER_APP_PATH" 2>/dev/null; then
    ok "Installed: $LAUNCHER_APP_PATH"
  else
    warn "Could not write to /Applications without elevated permissions"
    sudo mv "$STAGED_APP" "$LAUNCHER_APP_PATH" || die "Install failed"
    ok "Installed with sudo: $LAUNCHER_APP_PATH"
  fi

  # Nudge Launch Services so the app shows up in Spotlight immediately
  # instead of whenever macOS next feels like rescanning.
  local lsregister="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister"
  if [ -x "$lsregister" ]; then
    "$lsregister" -f "$LAUNCHER_APP_PATH" >/dev/null 2>&1 || true
    ok "Registered with Launch Services"
  fi

  rm -rf "$BUILD_DIR"
}


# ---------------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------------
main() {
  say "${C_BOLD}Building \"${LAUNCHER_APP_NAME}\" launcher${C_RESET}"

  create_skeleton
  write_executable
  write_info_plist
  copy_icon
  sign_bundle
  install_bundle

  header "Done"
  say "Launch it from Spotlight as \"${LAUNCHER_APP_NAME}\", or drag it to your Dock:"
  say "  open /Applications"
  say ""
  say "To inspect what it actually runs:"
  say "  cat \"$LAUNCHER_APP_PATH/Contents/MacOS/$EXECUTABLE_NAME\""
}

main "$@"
