# lib/common.sh
#
# Output helpers and small shared utilities.
#
# SOURCED ONLY BY bin/claude-profiles, never by an interactive shell. That
# distinction matters: this file defines a function called `say`, which would
# shadow the real macOS text-to-speech command if it ever landed in someone's
# ~/.zshrc. The shell integration is generated by `claude-profiles shell-init`
# and deliberately shares no code with this file — see shell/init.zsh.
#
# Nothing here sets `set -e`. Safety flags belong to the entrypoint, so that
# a library can never change the error behaviour of whatever sourced it.
# ---------------------------------------------------------------------------

# Colours are disabled when stderr is not a terminal, so piping to a file or
# a CI log does not fill it with escape codes.
#
# Note: the check is on stderr (fd 2), not stdout. All human-facing chatter
# goes to stderr precisely so that `list --json` and `doctor --json` can put
# clean machine-readable output on stdout with no risk of interleaving.
# shellcheck disable=SC2034  # consumed by bin/claude-profiles and lib/*.sh
if [ -t 2 ] && [ -z "${NO_COLOR:-}" ]; then
  C_RESET=$'\033[0m'
  C_BOLD=$'\033[1m'
  C_DIM=$'\033[2m'
  C_RED=$'\033[31m'
  C_GREEN=$'\033[32m'
  C_YELLOW=$'\033[33m'
  C_BLUE=$'\033[34m'
  # One accent, used for headings and the active profile. Truecolor where the
  # terminal says it has it, the nearest 256-colour cell otherwise.
  case "${COLORTERM:-}" in
    truecolor|24bit) C_ACCENT=$'\033[38;2;217;119;87m' ;;
    *)               C_ACCENT=$'\033[38;5;173m' ;;
  esac
else
  C_RESET="" C_BOLD="" C_DIM="" C_RED="" C_GREEN="" C_YELLOW="" C_BLUE="" C_ACCENT=""
fi

# Status glyphs. UTF-8 when the locale can render it, plain ASCII otherwise,
# so a C-locale CI log or a Windows console still lines up.
case "${LC_ALL:-${LC_CTYPE:-${LANG:-}}}" in
  *UTF-8*|*utf-8*|*UTF8*|*utf8*)
    G_OK="✓" G_WARN="!" G_FAIL="✗" G_INFO="·" G_HEAD="▍" G_ON="●" G_OFF="○" ;;
  *)
    G_OK="+" G_WARN="!" G_FAIL="x" G_INFO="-" G_HEAD="#" G_ON="*" G_OFF="-" ;;
esac

# tilde <text> — $HOME spelled as ~ for human output. Paths are long enough
# already; the home prefix is the least informative part of every one.
tilde() {
  # The replacement comes from a variable: a literal ~ there is tilde-expanded
  # back into $HOME by bash 4.3+, and a quoted one keeps its backslash on 3.2.
  local s="$1" t='~'
  if [ -n "${HOME:-}" ] && [ "$HOME" != "/" ]; then s="${s//"$HOME"/$t}"; fi
  printf '%s' "$s"
}

# say    — normal progress message
# ok     — something succeeded / a check passed
# warn   — something is off but not fatal
# fail   — a check failed (does NOT exit; the caller decides)
# info   — supporting detail
# die    — fatal, prints and exits 1
# header — section divider

say()    { printf '%s\n' "$*" >&2; }
ok()     { printf '  %s%s%s %s\n' "$C_GREEN"  "$G_OK"   "$C_RESET" "$(tilde "$*")" >&2; }
warn()   { printf '  %s%s%s %s\n' "$C_YELLOW" "$G_WARN" "$C_RESET" "$(tilde "$*")" >&2; }
fail()   { printf '  %s%s%s %s\n' "$C_RED"    "$G_FAIL" "$C_RESET" "$(tilde "$*")" >&2; }
info()   { printf '  %s%s %s%s\n' "$C_DIM"    "$G_INFO" "$(tilde "$*")" "$C_RESET" >&2; }
die()    { printf '%s%s error:%s %s\n' "$C_RED" "$G_FAIL" "$C_RESET" "$(tilde "$*")" >&2; exit 1; }

header() { printf '\n%s%s%s %s%s%s\n' "$C_ACCENT" "$G_HEAD" "$C_RESET" "$C_BOLD" "$*" "$C_RESET" >&2; }

# confirm <prompt>
#
# Returns 0 only on an explicit y/yes. Anything else — including a stray
# keypress, EOF, or a closed stdin in CI — is a no. Every destructive path in
# this tool goes through here.
#
# CLAUDE_PROFILES_ASSUME_YES=1 bypasses it, for scripted installs. That is an
# opt-in the caller has to set deliberately; there is no --yes flag on
# individual destructive subcommands, because a flag is too easy to copy out
# of a README without reading what it skips.
confirm() {
  local prompt="$1" reply=""

  if [ "${CLAUDE_PROFILES_ASSUME_YES:-}" = "1" ]; then
    info "$prompt — assuming yes (CLAUDE_PROFILES_ASSUME_YES=1)"
    return 0
  fi

  if [ ! -t 0 ]; then
    warn "$prompt — no terminal to ask on, assuming no"
    return 1
  fi

  printf '%s [y/N] ' "$prompt" >&2
  read -r reply || true
  case "${reply:-}" in
    [yY]|[yY][eE][sS]) return 0 ;;
    *) return 1 ;;
  esac
}


# read_secret <prompt>
#
# Reads one line with echo suppressed and prints it on stdout. Used for the
# OAuth token paste, so it never lands in terminal scrollback.
read_secret() {
  local prompt="$1" value=""
  printf '%s' "$prompt" >&2
  # `read -s` is a bash builtin; no external process ever sees the value.
  read -r -s value || true
  printf '\n' >&2
  printf '%s' "$value"
}


# ---------------------------------------------------------------------------
# JSON emission
# ---------------------------------------------------------------------------
# Small hand-rolled writers. There is no jq dependency anywhere in this tool:
# the documents it produces are shallow and fully known, so a general-purpose
# serializer would be more code than this and one more thing to install.

# json_escape <string> — escape a value for inclusion in a JSON string literal.
json_escape() {
  local s="$1"
  s=${s//\\/\\\\}
  s=${s//\"/\\\"}
  s=${s//$'\t'/\\t}
  s=${s//$'\n'/\\n}
  s=${s//$'\r'/\\r}
  printf '%s' "$s"
}

# json_decode <encoded> — inverse of the encoding lib/json.awk applies to the
# value field. Order matters: backslash last, or "\\t" would decode as a tab.
json_decode() {
  local s="$1" out="" c next i len
  len=${#s}
  i=0
  while [ "$i" -lt "$len" ]; do
    c=${s:$i:1}
    if [ "$c" = "\\" ]; then
      next=${s:$((i + 1)):1}
      case "$next" in
        t)  out="$out"$'\t'; i=$((i + 2)); continue ;;
        n)  out="$out"$'\n'; i=$((i + 2)); continue ;;
        r)  out="$out"$'\r'; i=$((i + 2)); continue ;;
        \\) out="$out\\";    i=$((i + 2)); continue ;;
      esac
    fi
    out="$out$c"
    i=$((i + 1))
  done
  printf '%s' "$out"
}


# ---------------------------------------------------------------------------
# Misc
# ---------------------------------------------------------------------------

# have <command> — is this executable on PATH?
have() { command -v "$1" >/dev/null 2>&1; }

# lower <string> — bash 3.2 has no ${var,,}, and macOS ships bash 3.2.
lower() { printf '%s' "$1" | tr '[:upper:]' '[:lower:]'; }

# ucfirst <string> — "work" -> "Work". Used for directory names, so that a
# profile called "work" gets ~/Library/Application Support/Claude-Work and
# matches what the pre-1.0 scripts created.
ucfirst() {
  local s="$1"
  [ -n "$s" ] || return 0
  printf '%s%s' "$(printf '%s' "${s:0:1}" | tr '[:lower:]' '[:upper:]')" "${s:1}"
}

# join_by <sep> <items...>
join_by() {
  local sep="$1"; shift
  local out=""
  local item
  for item in "$@"; do
    if [ -z "$out" ]; then out="$item"; else out="$out$sep$item"; fi
  done
  printf '%s' "$out"
}
